#!/bin/sh -eu
scriptdir="$(readlink -f `dirname $0`)"
cd "$1"

fmt () {
    printf "$1-%05d.png" "$2"
}

# Initial image
old="`fmt ts 0`"
cp "$scriptdir/initial.png" "$old"
frame=0

#convert -size 250x250 xc:white "$old"

jq -Rr 'capture("(?<ts>[0-9]*) Received request: (?<json>.*)") | .+ (.json | fromjson) | if .requestType == "postTile" then [((.ts | tonumber - 1551386389) / 20 | floor),.X,.Y]+[[219,0,5],[133,222,53],[0,0,255],[255,255,255],[0,0,0],[26,203,213],[24,181,4],[255,153,51],[252,145,199],[255,255,0],[221,221,221],[117,117,117],[142,87,51],[13,109,187],[195,80,222],[110,0,108]][.colorID | tonumber]+[.userID] else empty end | @tsv' | while read ts x y r g b user; do
    new="`fmt ts $ts`"
    test "$new" = "$old" || frame=$(($frame + 1))
    convert "$old" -fill "rgb($r,$g,$b)" -draw "point $x,$y" "$new"
    ln -sf "$new" "`fmt frame $frame`"
    old="$new"
done

ffmpeg -r 30 -f image2 -i frame-%05d.png -vf scale=1000:1000:flags=neighbor -vcodec libx264 -crf 25 -pix_fmt yuv420p timelapse.mp4
