#!/bin/sh -eu

width=512
height=512
fps=30 # Timelapse frames per seconds
spf=10 # Seconds in real time per frame
scale=4 # Scaling factor for output video, multiplier for width & height

colors="`dirname $0`/colors.list"
urpo="`dirname $0`/urpo"

if test $# -ne 2; then
    echo "Usage $0 infile outfile" >&2
    exit 1
fi

jq --slurpfile c "$colors" -Rr 'capture("(?<ts>[0-9]*) Received request: (?<json>.*)") | .+ (.json | fromjson) | [.ts, .X, .Y] + ($c[.colorID | tonumber] // error("Unknown color " + .colorID)) | @tsv' <"$1" |
    "$urpo" "$width" "$height" "$spf" |
    ffmpeg -f rawvideo -pixel_format rgb24 -video_size "${width}x${height}" -framerate "$fps" -i - -vf scale=iw*"$scale":ih*"$scale":flags=neighbor "$2"
